//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkedANswer
    {
        public int id { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> stdid { get; set; }
        public Nullable<int> Qid { get; set; }
        public string @checked { get; set; }
    }
}
