//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Choice_Id { get; set; }
        public string Choice_Letter { get; set; }
        public string Choice_Desc { get; set; }
        public Nullable<int> Q_Id { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
