//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Online_Examination_SystemEntities : DbContext
    {
        public Online_Examination_SystemEntities()
            : base("name=Online_Examination_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Exam_Q> Exam_Q { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        public virtual int Course_update(Nullable<int> crs_id, string crs_name)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            var crs_nameParameter = crs_name != null ?
                new ObjectParameter("crs_name", crs_name) :
                new ObjectParameter("crs_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Course_update", crs_idParameter, crs_nameParameter);
        }
    
        public virtual ObjectResult<Crs_top_Report_Result> Crs_top_Report(Nullable<int> crs_Id)
        {
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("Crs_Id", crs_Id) :
                new ObjectParameter("Crs_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Crs_top_Report_Result>("Crs_top_Report", crs_IdParameter);
        }
    
        public virtual ObjectResult<string> DeleteChoice(Nullable<int> choiceId)
        {
            var choiceIdParameter = choiceId.HasValue ?
                new ObjectParameter("choiceId", choiceId) :
                new ObjectParameter("choiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteChoice", choiceIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteCourse(Nullable<int> crsId)
        {
            var crsIdParameter = crsId.HasValue ?
                new ObjectParameter("crsId", crsId) :
                new ObjectParameter("crsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteCourse", crsIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteDepartment(Nullable<int> deptId)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteDepartment", deptIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteExam(Nullable<int> examId)
        {
            var examIdParameter = examId.HasValue ?
                new ObjectParameter("examId", examId) :
                new ObjectParameter("examId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteExam", examIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteInstructor(Nullable<int> insId)
        {
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteInstructor", insIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteQuestion(Nullable<int> qId)
        {
            var qIdParameter = qId.HasValue ?
                new ObjectParameter("qId", qId) :
                new ObjectParameter("qId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteQuestion", qIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteStudent(Nullable<int> studId)
        {
            var studIdParameter = studId.HasValue ?
                new ObjectParameter("studId", studId) :
                new ObjectParameter("studId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteStudent", studIdParameter);
        }
    
        public virtual ObjectResult<string> DeleteTopic(Nullable<int> topId)
        {
            var topIdParameter = topId.HasValue ?
                new ObjectParameter("topId", topId) :
                new ObjectParameter("topId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteTopic", topIdParameter);
        }
    
        public virtual int department_update(Nullable<int> dep_id, string dep_name)
        {
            var dep_idParameter = dep_id.HasValue ?
                new ObjectParameter("dep_id", dep_id) :
                new ObjectParameter("dep_id", typeof(int));
    
            var dep_nameParameter = dep_name != null ?
                new ObjectParameter("dep_name", dep_name) :
                new ObjectParameter("dep_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("department_update", dep_idParameter, dep_nameParameter);
        }
    
        public virtual int Exam_Answers(Nullable<int> exam_id, Nullable<int> std_id, string a1, string a2, string a3, string a4, string a5, string a6, string a7, string a8, string a9, string a10)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var a1Parameter = a1 != null ?
                new ObjectParameter("A1", a1) :
                new ObjectParameter("A1", typeof(string));
    
            var a2Parameter = a2 != null ?
                new ObjectParameter("A2", a2) :
                new ObjectParameter("A2", typeof(string));
    
            var a3Parameter = a3 != null ?
                new ObjectParameter("A3", a3) :
                new ObjectParameter("A3", typeof(string));
    
            var a4Parameter = a4 != null ?
                new ObjectParameter("A4", a4) :
                new ObjectParameter("A4", typeof(string));
    
            var a5Parameter = a5 != null ?
                new ObjectParameter("A5", a5) :
                new ObjectParameter("A5", typeof(string));
    
            var a6Parameter = a6 != null ?
                new ObjectParameter("A6", a6) :
                new ObjectParameter("A6", typeof(string));
    
            var a7Parameter = a7 != null ?
                new ObjectParameter("A7", a7) :
                new ObjectParameter("A7", typeof(string));
    
            var a8Parameter = a8 != null ?
                new ObjectParameter("A8", a8) :
                new ObjectParameter("A8", typeof(string));
    
            var a9Parameter = a9 != null ?
                new ObjectParameter("A9", a9) :
                new ObjectParameter("A9", typeof(string));
    
            var a10Parameter = a10 != null ?
                new ObjectParameter("A10", a10) :
                new ObjectParameter("A10", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Exam_Answers", exam_idParameter, std_idParameter, a1Parameter, a2Parameter, a3Parameter, a4Parameter, a5Parameter, a6Parameter, a7Parameter, a8Parameter, a9Parameter, a10Parameter);
        }
    
        public virtual ObjectResult<ExamANDChoices_Result> ExamANDChoices(Nullable<int> examnum)
        {
            var examnumParameter = examnum.HasValue ?
                new ObjectParameter("Examnum", examnum) :
                new ObjectParameter("Examnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExamANDChoices_Result>("ExamANDChoices", examnumParameter);
        }
    
        public virtual int ExamCorrection1(Nullable<int> examNum, Nullable<int> stdtID)
        {
            var examNumParameter = examNum.HasValue ?
                new ObjectParameter("ExamNum", examNum) :
                new ObjectParameter("ExamNum", typeof(int));
    
            var stdtIDParameter = stdtID.HasValue ?
                new ObjectParameter("StdtID", stdtID) :
                new ObjectParameter("StdtID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExamCorrection1", examNumParameter, stdtIDParameter);
        }
    
        public virtual int GenerateExam(string crs_name, Nullable<int> mCQ, Nullable<int> t_F)
        {
            var crs_nameParameter = crs_name != null ?
                new ObjectParameter("Crs_name", crs_name) :
                new ObjectParameter("Crs_name", typeof(string));
    
            var mCQParameter = mCQ.HasValue ?
                new ObjectParameter("MCQ", mCQ) :
                new ObjectParameter("MCQ", typeof(int));
    
            var t_FParameter = t_F.HasValue ?
                new ObjectParameter("T_F", t_F) :
                new ObjectParameter("T_F", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateExam", crs_nameParameter, mCQParameter, t_FParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GenerateMCQ(string examCrsName, Nullable<int> p__MCQ)
        {
            var examCrsNameParameter = examCrsName != null ?
                new ObjectParameter("examCrsName", examCrsName) :
                new ObjectParameter("examCrsName", typeof(string));
    
            var p__MCQParameter = p__MCQ.HasValue ?
                new ObjectParameter("p__MCQ", p__MCQ) :
                new ObjectParameter("p__MCQ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GenerateMCQ", examCrsNameParameter, p__MCQParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GenerateTF(string examCrsName, Nullable<int> p__TF)
        {
            var examCrsNameParameter = examCrsName != null ?
                new ObjectParameter("examCrsName", examCrsName) :
                new ObjectParameter("examCrsName", typeof(string));
    
            var p__TFParameter = p__TF.HasValue ?
                new ObjectParameter("p__TF", p__TF) :
                new ObjectParameter("p__TF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GenerateTF", examCrsNameParameter, p__TFParameter);
        }
    
        public virtual ObjectResult<string> getChoiceA(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getChoiceA", q_idParameter);
        }
    
        public virtual ObjectResult<string> getChoiceB(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getChoiceB", q_idParameter);
        }
    
        public virtual ObjectResult<string> getChoiceC(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getChoiceC", q_idParameter);
        }
    
        public virtual ObjectResult<string> getChoiceD(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getChoiceD", q_idParameter);
        }
    
        public virtual ObjectResult<getQue_Result> getQue(Nullable<int> exam_Id, Nullable<int> q_number)
        {
            var exam_IdParameter = exam_Id.HasValue ?
                new ObjectParameter("Exam_Id", exam_Id) :
                new ObjectParameter("Exam_Id", typeof(int));
    
            var q_numberParameter = q_number.HasValue ?
                new ObjectParameter("Q_number", q_number) :
                new ObjectParameter("Q_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getQue_Result>("getQue", exam_IdParameter, q_numberParameter);
        }
    
        public virtual ObjectResult<Ins_Crs_Report_Result> Ins_Crs_Report(Nullable<int> ins_id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_Crs_Report_Result>("Ins_Crs_Report", ins_idParameter);
        }
    
        public virtual ObjectResult<string> InsertChoice(Nullable<int> choiceID, string choiceDesc, Nullable<int> qID)
        {
            var choiceIDParameter = choiceID.HasValue ?
                new ObjectParameter("ChoiceID", choiceID) :
                new ObjectParameter("ChoiceID", typeof(int));
    
            var choiceDescParameter = choiceDesc != null ?
                new ObjectParameter("choiceDesc", choiceDesc) :
                new ObjectParameter("choiceDesc", typeof(string));
    
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertChoice", choiceIDParameter, choiceDescParameter, qIDParameter);
        }
    
        public virtual ObjectResult<string> InsertCourse(Nullable<int> crsID, string crsName, Nullable<int> topicID)
        {
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("CrsID", crsID) :
                new ObjectParameter("CrsID", typeof(int));
    
            var crsNameParameter = crsName != null ?
                new ObjectParameter("CrsName", crsName) :
                new ObjectParameter("CrsName", typeof(string));
    
            var topicIDParameter = topicID.HasValue ?
                new ObjectParameter("TopicID", topicID) :
                new ObjectParameter("TopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertCourse", crsIDParameter, crsNameParameter, topicIDParameter);
        }
    
        public virtual ObjectResult<string> InsertDepartment(Nullable<int> deptID, string deptName)
        {
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("DeptID", deptID) :
                new ObjectParameter("DeptID", typeof(int));
    
            var deptNameParameter = deptName != null ?
                new ObjectParameter("DeptName", deptName) :
                new ObjectParameter("DeptName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertDepartment", deptIDParameter, deptNameParameter);
        }
    
        public virtual ObjectResult<string> InsertExam(Nullable<int> examID, Nullable<System.DateTime> examDate, Nullable<int> stdID, Nullable<int> crsID, Nullable<int> grade)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(int));
    
            var examDateParameter = examDate.HasValue ?
                new ObjectParameter("ExamDate", examDate) :
                new ObjectParameter("ExamDate", typeof(System.DateTime));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("StdID", stdID) :
                new ObjectParameter("StdID", typeof(int));
    
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("CrsID", crsID) :
                new ObjectParameter("CrsID", typeof(int));
    
            var gradeParameter = grade.HasValue ?
                new ObjectParameter("Grade", grade) :
                new ObjectParameter("Grade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertExam", examIDParameter, examDateParameter, stdIDParameter, crsIDParameter, gradeParameter);
        }
    
        public virtual ObjectResult<string> InsertExamQ(Nullable<int> examID, Nullable<int> qID, Nullable<int> q_Number, string checkedANS)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(int));
    
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(int));
    
            var q_NumberParameter = q_Number.HasValue ?
                new ObjectParameter("Q_Number", q_Number) :
                new ObjectParameter("Q_Number", typeof(int));
    
            var checkedANSParameter = checkedANS != null ?
                new ObjectParameter("checkedANS", checkedANS) :
                new ObjectParameter("checkedANS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertExamQ", examIDParameter, qIDParameter, q_NumberParameter, checkedANSParameter);
        }
    
        public virtual ObjectResult<string> InsertInsCrs(Nullable<int> insID, Nullable<int> crsID)
        {
            var insIDParameter = insID.HasValue ?
                new ObjectParameter("InsID", insID) :
                new ObjectParameter("InsID", typeof(int));
    
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("CrsID", crsID) :
                new ObjectParameter("CrsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertInsCrs", insIDParameter, crsIDParameter);
        }
    
        public virtual ObjectResult<string> InsertInstructor(Nullable<int> insID, string insFullname, string insUsername, string insPassword, Nullable<int> deptID)
        {
            var insIDParameter = insID.HasValue ?
                new ObjectParameter("InsID", insID) :
                new ObjectParameter("InsID", typeof(int));
    
            var insFullnameParameter = insFullname != null ?
                new ObjectParameter("InsFullname", insFullname) :
                new ObjectParameter("InsFullname", typeof(string));
    
            var insUsernameParameter = insUsername != null ?
                new ObjectParameter("InsUsername", insUsername) :
                new ObjectParameter("InsUsername", typeof(string));
    
            var insPasswordParameter = insPassword != null ?
                new ObjectParameter("InsPassword", insPassword) :
                new ObjectParameter("InsPassword", typeof(string));
    
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("DeptID", deptID) :
                new ObjectParameter("DeptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertInstructor", insIDParameter, insFullnameParameter, insUsernameParameter, insPasswordParameter, deptIDParameter);
        }
    
        public virtual ObjectResult<string> InsertOuestion(Nullable<int> qID, string qType, string qDesc, Nullable<int> crsID, string modelAnswer)
        {
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(int));
    
            var qTypeParameter = qType != null ?
                new ObjectParameter("QType", qType) :
                new ObjectParameter("QType", typeof(string));
    
            var qDescParameter = qDesc != null ?
                new ObjectParameter("QDesc", qDesc) :
                new ObjectParameter("QDesc", typeof(string));
    
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("crsID", crsID) :
                new ObjectParameter("crsID", typeof(int));
    
            var modelAnswerParameter = modelAnswer != null ?
                new ObjectParameter("ModelAnswer", modelAnswer) :
                new ObjectParameter("ModelAnswer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertOuestion", qIDParameter, qTypeParameter, qDescParameter, crsIDParameter, modelAnswerParameter);
        }
    
        public virtual ObjectResult<string> InsertStuCrs(Nullable<int> stdID, Nullable<int> crsID)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("StdID", stdID) :
                new ObjectParameter("StdID", typeof(int));
    
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("CrsID", crsID) :
                new ObjectParameter("CrsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertStuCrs", stdIDParameter, crsIDParameter);
        }
    
        public virtual ObjectResult<string> InsertStudent(Nullable<int> stdID, string stdFullname, string stdUsername, string stdPassword)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("StdID", stdID) :
                new ObjectParameter("StdID", typeof(int));
    
            var stdFullnameParameter = stdFullname != null ?
                new ObjectParameter("StdFullname", stdFullname) :
                new ObjectParameter("StdFullname", typeof(string));
    
            var stdUsernameParameter = stdUsername != null ?
                new ObjectParameter("StdUsername", stdUsername) :
                new ObjectParameter("StdUsername", typeof(string));
    
            var stdPasswordParameter = stdPassword != null ?
                new ObjectParameter("StdPassword", stdPassword) :
                new ObjectParameter("StdPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertStudent", stdIDParameter, stdFullnameParameter, stdUsernameParameter, stdPasswordParameter);
        }
    
        public virtual ObjectResult<string> InsertTopic(Nullable<int> topicID, string topName)
        {
            var topicIDParameter = topicID.HasValue ?
                new ObjectParameter("TopicID", topicID) :
                new ObjectParameter("TopicID", typeof(int));
    
            var topNameParameter = topName != null ?
                new ObjectParameter("TopName", topName) :
                new ObjectParameter("TopName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertTopic", topicIDParameter, topNameParameter);
        }
    
        public virtual int instructor_update(Nullable<int> instructor_id, string ins_name)
        {
            var instructor_idParameter = instructor_id.HasValue ?
                new ObjectParameter("instructor_id", instructor_id) :
                new ObjectParameter("instructor_id", typeof(int));
    
            var ins_nameParameter = ins_name != null ?
                new ObjectParameter("ins_name", ins_name) :
                new ObjectParameter("ins_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("instructor_update", instructor_idParameter, ins_nameParameter);
        }
    
        public virtual ObjectResult<string> LoginRegInstructor(string userName, Nullable<int> password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password.HasValue ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LoginRegInstructor", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> LoginRegStd(string userName, Nullable<int> password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password.HasValue ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LoginRegStd", userNameParameter, passwordParameter);
        }
    
        public virtual int question_update(Nullable<int> q_id, string q_ans)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            var q_ansParameter = q_ans != null ?
                new ObjectParameter("q_ans", q_ans) :
                new ObjectParameter("q_ans", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("question_update", q_idParameter, q_ansParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> randomExam(Nullable<int> crs_id)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("randomExam", crs_idParameter);
        }
    
        public virtual ObjectResult<ReportStudentExamAnswer_Result> ReportStudentExamAnswer(Nullable<int> examNum, Nullable<int> stdID)
        {
            var examNumParameter = examNum.HasValue ?
                new ObjectParameter("ExamNum", examNum) :
                new ObjectParameter("ExamNum", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("StdID", stdID) :
                new ObjectParameter("StdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportStudentExamAnswer_Result>("ReportStudentExamAnswer", examNumParameter, stdIDParameter);
        }
    
        public virtual ObjectResult<SelectChoice_Result> SelectChoice(Nullable<int> choice_id)
        {
            var choice_idParameter = choice_id.HasValue ?
                new ObjectParameter("choice_id", choice_id) :
                new ObjectParameter("choice_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectChoice_Result>("SelectChoice", choice_idParameter);
        }
    
        public virtual ObjectResult<SelectCourse_Result> SelectCourse(Nullable<int> course_id)
        {
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCourse_Result>("SelectCourse", course_idParameter);
        }
    
        public virtual ObjectResult<SelectDepartment_Result> SelectDepartment(Nullable<int> dept_id)
        {
            var dept_idParameter = dept_id.HasValue ?
                new ObjectParameter("Dept_id", dept_id) :
                new ObjectParameter("Dept_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDepartment_Result>("SelectDepartment", dept_idParameter);
        }
    
        public virtual ObjectResult<SelectExam_Result> SelectExam(Nullable<int> exam_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectExam_Result>("SelectExam", exam_idParameter);
        }
    
        public virtual ObjectResult<SelectExamQ_Result> SelectExamQ(Nullable<int> exam_id, Nullable<int> q_Id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            var q_IdParameter = q_Id.HasValue ?
                new ObjectParameter("Q_Id", q_Id) :
                new ObjectParameter("Q_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectExamQ_Result>("SelectExamQ", exam_idParameter, q_IdParameter);
        }
    
        public virtual ObjectResult<SelectIns_Crs_Result> SelectIns_Crs(Nullable<int> ins_id, Nullable<int> crs_Id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("Ins_id", ins_id) :
                new ObjectParameter("Ins_id", typeof(int));
    
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("Crs_Id", crs_Id) :
                new ObjectParameter("Crs_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIns_Crs_Result>("SelectIns_Crs", ins_idParameter, crs_IdParameter);
        }
    
        public virtual ObjectResult<SelectInstructor_Result> SelectInstructor(Nullable<int> ins_id)
        {
            var ins_idParameter = ins_id.HasValue ?
                new ObjectParameter("ins_id", ins_id) :
                new ObjectParameter("ins_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectInstructor_Result>("SelectInstructor", ins_idParameter);
        }
    
        public virtual ObjectResult<SelectQuestion_Result> SelectQuestion(Nullable<int> q_id)
        {
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("Q_id", q_id) :
                new ObjectParameter("Q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectQuestion_Result>("SelectQuestion", q_idParameter);
        }
    
        public virtual ObjectResult<SelectStu_Crs_Result> SelectStu_Crs(Nullable<int> stu_id, Nullable<int> crs_id)
        {
            var stu_idParameter = stu_id.HasValue ?
                new ObjectParameter("stu_id", stu_id) :
                new ObjectParameter("stu_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("Crs_id", crs_id) :
                new ObjectParameter("Crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStu_Crs_Result>("SelectStu_Crs", stu_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<SelectStudent_Result> SelectStudent(Nullable<int> std_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStudent_Result>("SelectStudent", std_idParameter);
        }
    
        public virtual ObjectResult<SelectTopic_Result> SelectTopic(Nullable<int> top_id)
        {
            var top_idParameter = top_id.HasValue ?
                new ObjectParameter("top_id", top_id) :
                new ObjectParameter("top_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTopic_Result>("SelectTopic", top_idParameter);
        }
    
        public virtual ObjectResult<std_Dept_Report_Result> std_Dept_Report(Nullable<int> dept_Id)
        {
            var dept_IdParameter = dept_Id.HasValue ?
                new ObjectParameter("Dept_Id", dept_Id) :
                new ObjectParameter("Dept_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<std_Dept_Report_Result>("std_Dept_Report", dept_IdParameter);
        }
    
        public virtual ObjectResult<std_Grade_Report_Result> std_Grade_Report(Nullable<int> std_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<std_Grade_Report_Result>("std_Grade_Report", std_idParameter);
        }
    
        public virtual int std_update(Nullable<int> std_id, string std_name)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var std_nameParameter = std_name != null ?
                new ObjectParameter("std_name", std_name) :
                new ObjectParameter("std_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("std_update", std_idParameter, std_nameParameter);
        }
    
        public virtual int topic_update(Nullable<int> top_id, string top_name)
        {
            var top_idParameter = top_id.HasValue ?
                new ObjectParameter("top_id", top_id) :
                new ObjectParameter("top_id", typeof(int));
    
            var top_nameParameter = top_name != null ?
                new ObjectParameter("top_name", top_name) :
                new ObjectParameter("top_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("topic_update", top_idParameter, top_nameParameter);
        }
    }
}
